config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users
    
    root 'posts#index'

    resources :posts, only: [:show, :index]
    resources :tags, only: :show
    resources :categories, only: :show

    namespace :admin do
      resources :categories, except: :show
      resources :posts, except: [:show, :index]
      resources :pictures, only: [:create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  
  validates :name, presence: true

  has_ancestry
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :category, optional: true

  validates :title, :summary, :body, presence: true

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(', ').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings
  has_many :posts, through: :taggings


  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("name, taggings.tag_id")
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :trackable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"

  protected

  def check_admin
    redirect_to root_path, alert: 'You have no access to this page' unless current_user.admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :authenticate_user!
  before_action :set_category, only: [:edit, :update, :destroy ]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, success: 'Категория успешно создана'
    else
      @categories = Category.all.order(:name)
      flash[:danger] = 'Категория не создана'
      render :new
    end
  end

  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, success: 'Категория успешно обновлена'
    else
      @categories = Category.where("id != #{@category.id}").order(:name)
      flash[:danger] = 'Категория не обновлена'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, success: 'Категория успешно удалена'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < ApplicationController
  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => { url: @picture.image.url(:large), picture_id: @picture.id } }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok } }
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  before_action :authenticate_user!
  before_action :set_post, only: [:edit, :update, :destroy]


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Article was successfully created'
    else
      flash.now[:danger] = 'Article was not created'
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, success: 'Article was successfully updated'
    else
      flash.now[:danger] = 'Article was not updated'
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Article was successfully deleted'
  end

  private

  def post_params
    params.require(:post).permit(:title, :summary, :body, :image, :all_tags, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger, :info, :warning

  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def show
    @posts = Post.where(category_id: [@category.subtree_ids]).paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!

  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => { url: @picture.image.url(:large), picture_id: @picture.id } }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok } }
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :show

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def build_breadcrumb(category)
    result = []
    category.ancestors.each do |ancestor|
      result << content_tag(:li, class: "breadcrumb-item") do
        link_to(ancestor.name, ancestor)
      end
    end
    result << content_tag(:li, category.name, class: "breadcrumb-item active")
    result.join('').html_safe
  end

  def bootstrap_class_for(name)
    { success:"alert-success",
      error:  "alert-danger",
      danger: "alert-danger",
      alert:  "alert-warning",
      notice: "alert-info"
    }[name.to_sym] || name
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/admin/categories/_form.html.slim
- if @category.errors.any?
  .alert.alert-danger
    h5= t('common.errors')
    ul
      -@category.errors.full_messages.each do |message|
        li= message
= form_for [:admin, @category], html: { multipart: true } do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :parent_id
    = f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control'
  .btn-group
    = f.submit t('.submit', action: @category.new_record? ? t('common.new') : t('common.edit')), class: 'btn btn-primary'
    = link_to t('common.back'), :back, class: 'btn btn-outline-secondary'

app/views/admin/categories/edit.html.slim
h1= t('.title')

= render 'form'

app/views/admin/categories/index.html.slim
h1= t('.title')

.buttons_panel
  = link_to 'New Category', new_admin_category_path, class: 'btn btn-outline-primary btn-sm'
  
section#categories
  table.table
    thead
      tr
        td #
        th Name
        th Parent Category
        th Actions
    tbody
      - @categories.each_with_index do |category, index|
        tr
          th= index + 1
          th= category.name
          th= category.parent.name if category.parent.present?
          th
            = link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-outline-primary btn-sm'
            = link_to 'Delete', admin_category_path(category), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-outline-danger btn-sm'

app/views/admin/categories/new.html.slim
h1= t('.title')

= render 'form'

app/views/admin/posts/_form.html.slim
- if @post.errors.any?
  .alert.alert-danger
    h5= t('common.errors')
    ul
      -@post.errors.full_messages.each do |message|
        li= message
= form_for [:admin, @post], html: { multipart: true } do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :summary
    = f.text_area :summary, class: 'form-control'
  .form-group
    = f.label :body
    = f.trix_editor :body, class: 'editor'
  .form-group
    = f.label :category_id
    = f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true }, class: 'form-control'
  .form-group
    = f.label :all_tags
    = f.text_field :all_tags, class: 'form-control'
  .form-group
    = f.file_field :image      
  .btn-group
    = f.submit t('.submit', action: @post.new_record? ? t('common.new') : t('common.edit')), class: 'btn btn-primary'
    = link_to t('common.back'), :back, class: 'btn btn-outline-secondary'

app/views/admin/posts/edit.html.slim
h1= t('.title')

= render 'form'

app/views/admin/posts/new.html.slim
h1= t('.title')

= render 'form'

app/views/categories/_form.html.slim
- if @category.errors.any?
  .alert.alert-danger
    h5= t('common.errors')
    ul
      -@category.errors.full_messages.each do |message|
        li= message
= form_for @category, html: { multipart: true } do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :parent_id
    = f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: 'form-control'
  .btn-group
    = f.submit t('.submit', action: @category.new_record? ? t('common.new') : t('common.edit')), class: 'btn btn-primary'
    = link_to t('common.back'), :back, class: 'btn btn-outline-secondary'

app/views/categories/index.html.slim
h1= t('.title')

.buttons_panel
  = link_to 'New Category', new_category_path, class: 'btn btn-outline-primary btn-sm'
  
section#categories
  table.table
    thead
      tr
        td #
        th Name
        th Parent Category
        th Actions
    tbody
      - @categories.each_with_index do |category, index|
        tr
          th= index + 1
          th= category.name
          th= category.parent.name if category.parent.present?
          th
            = link_to 'Edit', edit_category_path(category), class: 'btn btn-outline-primary btn-sm'
            = link_to 'Delete', category_path(category), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-outline-danger btn-sm'

app/views/categories/show.html.slim
= render 'shared/breadcrumb', category: @category

h1= @category.name

section#posts
  =render @posts
  
= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer'

app/views/categories/show.js.erb
$('#posts').append("<%= j render(partial: 'posts/delimeter') %>");
$('#posts').append("<%= j render(@posts) %>");

<% if @posts.next_page %>
    $('.pagination').replaceWith("<%= j  will_paginate(@posts, renderer: 'BootstrapPaginationHelper::LinkRenderer') %>");
<% else %>
    $('.pagination').remove();
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
              <a class="nav-link" href="<%= root_path %>"><%= t('posts.index.title')%></a>
            </li>
            <% Category.order(:name).roots.each do |category| %>
              <li class="nav-item <%= 'active' if current_page?(category_path(category)) %>">
                <%= link_to category.name, category, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <ul class="navbar-nav pull-xs-right">
            <li class="nav-item <%= "active" if I18n.locale == :ru %>">
              <%= link_to "RU", { locale: :ru }, class: 'nav-link' %>
            </li>
            <li class="nav-item <%= "active" if I18n.locale == :en %>">
              <%= link_to "EN", { locale: :en }, class: 'nav-link' %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>              
              <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
                <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
      </nav>
    </div>
    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-9">
          <%= yield %>
        </div>
        <div class="col-md-3">
          <%= render 'shared/submenu'%>
          <div class="tag_cloud">
            <h2>Tags</h2>
            <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
              <a class="nav-link" href="<%= root_path %>"><%= t('posts.index.title')%></a>
            </li>
            <% Category.order(:name).roots.each do |category| %>
              <li class="nav-item <%= 'active' if current_page?(category_path(category)) %>">
                <%= link_to category.name, category, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <ul class="navbar-nav pull-xs-right">
            <li class="nav-item <%= "active" if I18n.locale == :ru %>">
              <%= link_to "RU", { locale: :ru }, class: 'nav-link' %>
            </li>
            <li class="nav-item <%= "active" if I18n.locale == :en %>">
              <%= link_to "EN", { locale: :en }, class: 'nav-link' %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>              
              <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item <%= 'active' if current_page?(root_path) || current_page?(posts_path) %>">
                <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
      </nav>
    </div>
    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-9">
          <%= yield %>
        </div>
        <div class="col-md-3">
          <%= render 'shared/submenu'%>
          <div class="tag_cloud">
            <h2>Tags</h2>
            <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/_delimeter.html.slim
.page_delimeter
  | Page 
  = params[:page]

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/

var disqus_config = function () {
  <%# <1%# this.page.url = '<%= request.base.url + request.original_fullpath %2>'; %>
  this.page.url = 'http://localhost.com<%= request.original_fullpath%>';  // Replace PAGE_URL with your page's canonical URL variable
  this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

  (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://edublo.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.slim
- if @post.errors.any?
  .alert.alert-danger
    h5= t('common.errors')
    ul
      -@post.errors.full_messages.each do |message|
        li= message
= form_for @post, html: { multipart: true } do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :summary
    = f.text_area :summary, class: 'form-control'
  .form-group
    = f.label :body
    = f.trix_editor :body, class: 'editor'
  .form-group
    = f.label :category_id
    = f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true }, class: 'form-control'
  .form-group
    = f.label :all_tags
    = f.text_field :all_tags, class: 'form-control'
  .form-group
    = f.file_field :image      
  .btn-group
    = f.submit t('.submit', action: @post.new_record? ? t('common.new') : t('common.edit')), class: 'btn btn-primary'
    = link_to t('common.back'), :back, class: 'btn btn-outline-secondary'

app/views/posts/_post.html.slim
article.post
  section.post-head
    h2= link_to post.title, post_path(post)
    small
      time= post.created_at.to_date.strftime("%d %B, %Y")
      - if post.category.present?
        '  |
        =link_to post.category.name, post.category
      - if user_signed_in? && current_user.admin?
        '  |
        =link_to t('common.edit'), edit_admin_post_path(post)
        '  |
        =link_to t('common.delete'), admin_post_path(post), method: :delete, data: {confirm: 'Are you sure?'}      
  section.post-summary.clearfix
    = image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image?
    = post.summary
  section.footer-summary
    = raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'badge badge-primary' }.join(' ')

app/views/posts/index.html.slim
h1= t('.title')

- if user_signed_in? && current_user.admin?
  = link_to t('admin.posts.new.title'), new_admin_post_path, class: 'btn btn-outline-primary btn-sm'

section id='posts'
  =render @posts

=will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer'

app/views/posts/index.js.erb
$('#posts').append("<%= j render(partial: 'delimeter') %>");
$('#posts').append("<%= j render(@posts) %>");

<% if @posts.next_page %>
    $('.pagination').replaceWith("<%= j  will_paginate(@posts, renderer: 'BootstrapPaginationHelper::LinkRenderer') %>");
<% else %>
    $('.pagination').remove();
<% end %>

app/views/posts/show.html.slim
= render 'shared/breadcrumb', category: @post.category

article.post
  section.post-head
    h1= @post.title
    small
      time= @post.created_at.to_date.strftime("%d %B, %Y")
      - if @post.category.present?
        '  |      
        =link_to @post.category.name, @post.category
      - if user_signed_in? && current_user.admin?
        '  |
        =link_to 'Edit', edit_admin_post_path(@post)
        '  |
        =link_to 'Delete', admin_post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}
 
  section.post-body
    = image_tag @post.image.url(:large), class: 'image-show' if @post.image?
    = @post.body.html_safe
= render 'disqus'

app/views/shared/_breadcrumb.html.slim
- if category.present? && category.parent_id
  ol.breadcrumb
    = build_breadcrumb(category)

app/views/shared/_submenu.html.slim
.submenu
  h2 Categories
  ul.nav.nav-pills.nav-stacked
    - Category.roots.each do |category|
      li.nav-item
        = link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? && @post.category == category}"
        = render 'shared/submenu_categories', categories: category.root.descendants.arrange

app/views/shared/_submenu_categories.html.slim
ul.nav.nav-pills.nav-stacked.nested_nav
  - categories.each do |category, children|
    li
      = link_to category.name, category, class: "nav-link #{'active' if current_page?(category_path(category)) || @post.present? && @post.category == category}"
      = render 'shared/submenu_categories', categories: children if children.present?

app/views/tags/show.html.slim
h1= @tag.name

- if @tag.posts.empty?
  =h2 No Posts
- else
  = render @tag.posts